### ISSUE TITLE
@macro rendered in views

### ISSUE THREAD

**Issue by samijnih** [RobinRadic/blade-extensions#21] opened 2015-06-21 20:42 UTC
Hello,

Here's my composer
            "php": ">=5.5.9",
            "laravel/framework": "5.1.*",
            "illuminate/html": "5.*",
            "kozz/laravel-guzzle-provider": "6.0",
            "caouecs/laravel4-lang": "~2.0",
            "nesbot/carbon": "~1.14",
            "radic/blade-extensions": "~4.0",
            "laravelcollective/html": "5.1.*",
            "raveren/kint": ">=0.9.1",
            "erusev/parsedown": "~1.5"

I added in config/app.php for providers : 
Collective\Html\HtmlServiceProvider::class,
Radic\BladeExtensions\BladeExtensionsServiceProvider::class

I added aliases:
'Form'      => Collective\Html\FormFacade::class,
'HTML'      => Collective\Html\HtmlFacade::class,

My template contains :
@macro('simple', $first, $second = 3, $what)
    $who = $first . $second;
    return $what . $who;
@endmacro

which is rendered as text with @domacro('simple')

Laravel 5.1

**Comment by RobinRadic** [comment] 2015-06-21 23:41
After checking i'm fairly sure that's a problem with the alias 'Form'. I've made a silly mistake of using lowercase 'form' instead of 'Form' inside both the service provider and config file.

So until i fix it properly, also alias `'form' => Collective\Html\FormFacade::class`. That should fix it.

I guess it's better to give people the option to configure the Form alias inside the `blade-extensions.php` config file. Will implement it next version.

Thanks

**Comment by samijnih** [comment] 2015-06-22 08:22
Hello,

I changed 'Form' with 'form' but the macro is still rendering as a text :/

**Comment by RobinRadic** [comment] 2015-06-22 12:01
That should mean the BladeExtensionsServiceProvider skips adding those directives. 

Im not in a position i can test stuff, but i've checked some code and found out it's not a problem with upper/lowercase differences like i mentioned previously. The HtmlServiceProvider->register is already doing the alias for 'form'.

```php
$this->app->alias('html', 'Collective\Html\HtmlBuilder');
$this->app->alias('form', 'Collective\Html\FormBuilder');
```

The only think i can think of right now is attaching it yourself as temporary workaround. `Radic\BladeExtensions\Directives\MacroDirectives::attach($this->app);` . Put it in a service provider's register method. That should certainly do the trick.

**Comment by samijnih** [comment] 2015-06-22 12:19
I added \Radic\BladeExtensions\Directives\MacroDirectives::attach($this->app); in AppServiceProvider.php and it worked

**Comment by RobinRadic** [comment] 2015-06-22 13:27
Good to hear. Then i know what the problem is aswell. Will be fixed soon. Thanks.

**Comment by samijnih** [comment] 2015-06-22 13:38
No problem, I like your works for this project

**Comment by samijnih** [comment] 2015-06-22 20:09
I've got a question :

Is it normal when I do
<a href="@domacro('generateProfileUrl', $response->user->username)">{{ $response->user->username }}</a>

that it make me a blank page?

I don't want that my macro generate the entire <a href> because if I want to add some attribute, I'll have to overload parameters like this

@macro('generateProfileUrl', $username, $params = array())
    return '<a class="' . ($params['class'] or '') . '" title="' . ($params['title'] or '') . '" href="' . $username . '">' . $username . '</a>';
@endmacro

I don't think this is beautiful

**Closed** 2015-06-23 01:39 UTC
Labels: bug, enhancement

**Comment by RobinRadic** [comment] 2015-06-23 01:58
I'm not entirely sure i understand.

Do you get a blank page with the first block of code you linked? If so, check your laravel.log file otherwise run a xdebug session to figure out what's the cause. I can't really help with that.

I've can verify that the macro directive at least should [work with that string](https://regex101.com/r/sL6kC2/1). Don't forget you can tinker around quite a bit in the `blade_extensions.php` config file. It contains all the php code that gets replaced. Specifically:


```php
    'directives' => array(
        // MacroDirective
        'doMacro' => <<<'EOT'
$1<?php
if(array_key_exists("form", $__env->getContainer()->getBindings())){
    echo app("form")->$2($3);
} ?>
EOT
    ,'openMacro' => <<<'EOT'
$1<?php
if(array_key_exists("form", $__env->getContainer()->getBindings())){
    app("form")->macro("$2", function($3){
EOT
    ,'closeMacro' => <<<'EOT'
    });
} ?>
EOT
```

If you continue having problems, please create a new issue and il pick it up from there. The initial  issue has been resolved with the latest commit :)
